# -*- coding: utf-8 -*-
"""NFL_Playoff.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15x6-O7ugfKgeInVzuxQ7BJa_y86BVJYo
"""



import pymc as pm
import re
import arviz as az
import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup, Comment
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import ipywidgets as widgets
from IPython.display import display
import streamlit as st

schedule_2025 = pd.read_csv('https://raw.githubusercontent.com/KrishnaRao1/NFL-passing-yards-model/refs/heads/main/data/Team_Schedule_2025.csv')






#Jordan Love
love_career = pd.read_csv('https://raw.githubusercontent.com/KrishnaRao1/NFL-passing-yards-model/refs/heads/main/data/love_career')
love_2025 = pd.read_csv('https://raw.githubusercontent.com/KrishnaRao1/NFL-passing-yards-model/refs/heads/main/data/love_2025')

#Justin Herbert
herbert_career = pd.read_csv('https://raw.githubusercontent.com/KrishnaRao1/NFL-passing-yards-model/refs/heads/main/data/herbert_career')
herbert_2025 = pd.read_csv('https://raw.githubusercontent.com/KrishnaRao1/NFL-passing-yards-model/refs/heads/main/data/herbert_2025')

#Josh Allen
allen_career = pd.read_csv('https://raw.githubusercontent.com/KrishnaRao1/NFL-passing-yards-model/refs/heads/main/data/allen_career')
allen_2025 = pd.read_csv("https://raw.githubusercontent.com/KrishnaRao1/NFL-passing-yards-model/refs/heads/main/data/allen_2025")



#Aaron Rodgers
rodgers_career = pd.read_csv("https://raw.githubusercontent.com/KrishnaRao1/NFL-passing-yards-model/refs/heads/main/data/rodgers_career")
rodgers_2025 = pd.read_csv("https://raw.githubusercontent.com/KrishnaRao1/NFL-passing-yards-model/refs/heads/main/data/rodgers_2025")

#Jalen Hurts
hurts_career = pd.read_csv("https://raw.githubusercontent.com/KrishnaRao1/NFL-passing-yards-model/refs/heads/main/data/hurts_career")
hurts_2025 = pd.read_csv("https://raw.githubusercontent.com/KrishnaRao1/NFL-passing-yards-model/refs/heads/main/data/hurts_2025")

#Trevor Lawrence
lawrence_career = pd.read_csv("https://raw.githubusercontent.com/KrishnaRao1/NFL-passing-yards-model/refs/heads/main/data/lawrence_career")
lawrence_2025 = pd.read_csv("https://raw.githubusercontent.com/KrishnaRao1/NFL-passing-yards-model/refs/heads/main/data/lawrence_2025")

#Matt Stafford
stafford_career = pd.read_csv("https://raw.githubusercontent.com/KrishnaRao1/NFL-passing-yards-model/refs/heads/main/data/stafford_career")
stafford_2025 = pd.read_csv("https://raw.githubusercontent.com/KrishnaRao1/NFL-passing-yards-model/refs/heads/main/data/stafford_2025")


#Brock Purdy
purdy_career = pd.read_csv("https://raw.githubusercontent.com/KrishnaRao1/NFL-passing-yards-model/refs/heads/main/data/purdy_career")
purdy_2025 = pd.read_csv("https://raw.githubusercontent.com/KrishnaRao1/NFL-passing-yards-model/refs/heads/main/data/purdy_2025")



passing_defense_2025 = pd.read_csv("https://raw.githubusercontent.com/KrishnaRao1/NFL-passing-yards-model/refs/heads/main/data/passing_defense_2025")

# --- Step 1: Clean and merge career stats for all QBs ---
# Make column names consistent for merging
love_clean = love_career.rename(columns={'Opponent': 'Opp_Team', 'YDS/G': 'Jordan Love'})
herbert_clean = herbert_career.rename(columns={'Opponent': 'Opp_Team', 'YDS/G': 'Justin Herbert'})
allen_clean = allen_career.rename(columns={'Opponent': 'Opp_Team', 'YDS/G': 'Josh Allen'})
rodgers_clean = rodgers_career.rename(columns={'Opponent': 'Opp_Team', 'YDS/G': 'Aaron Rodgers'})
hurts_clean = hurts_career.rename(columns={'Opponent': 'Opp_Team', 'YDS/G': 'Jalen Hurts'})
lawrence_clean = lawrence_career.rename(columns={'Opponent': 'Opp_Team', 'YDS/G': 'Trevor Lawrence'})
stafford_clean = stafford_career.rename(columns={'Opponent': 'Opp_Team', 'YDS/G': 'Matt Stafford'})
purdy_clean = purdy_career.rename(columns={'Opponent': 'Opp_Team', 'YDS/G': 'Brock Purdy'})

# Map full team names in defense_yards to abbreviations
team_name_map = {
    "Cardinals": "ARI", "Falcons": "ATL", "Ravens": "BAL", "Bills": "BUF",
    "Panthers": "CAR", "Bears": "CHI", "Bengals": "CIN", "Browns": "CLE",
    "Cowboys": "DAL", "Broncos": "DEN", "Lions": "DET", "Packers": "GB",
    "Texans": "HOU", "Colts": "IND", "Jaguars": "JAX", "Chiefs": "KC",
    "Raiders": "LV", "Chargers": "LAC", "Rams": "LAR", "Dolphins": "MIA",
    "Vikings": "MIN", "Patriots": "NE", "Saints": "NO", "Giants": "NYG",
    "Jets": "NYJ", "Eagles": "PHI", "Steelers": "PIT", "49ers": "SF",
    "Seahawks": "SEA", "Buccaneers": "TB", "Titans": "TEN", "Commanders": "WSH"
}





# Select defensive passing metric (example: Yards allowed per game)
def_metric = 'Y/G'  # replace with exact column name

scaler_def = StandardScaler()
passing_defense_2025['Def_pass_z'] = scaler_def.fit_transform(
    passing_defense_2025[[def_metric]]
)

# Make sure all 2025 season dataframes have 'Opp_Team' and 'YDS/G'
love_2025 = love_2025.rename(columns={'Opponent': 'Opp_Team', 'YDS/G': 'YDS/G'})
herbert_2025 = herbert_2025.rename(columns={'Opponent': 'Opp_Team', 'YDS/G': 'YDS/G'})
allen_2025 = allen_2025.rename(columns={'Opponent': 'Opp_Team', 'YDS/G': 'YDS/G'})
rodgers_2025 = rodgers_2025.rename(columns={'Opponent': 'Opp_Team', 'YDS/G': 'YDS/G'})
hurts_2025 = hurts_2025.rename(columns={'Opponent': 'Opp_Team', 'YDS/G': 'YDS/G'})
lawrence_2025 = lawrence_2025.rename(columns={'Opponent': 'Opp_Team', 'YDS/G': 'YDS/G'})
stafford_2025 = stafford_2025.rename(columns={'Opponent': 'Opp_Team', 'YDS/G': 'YDS/G'})
purdy_2025 = purdy_2025.rename(columns={'Opponent': 'Opp_Team', 'YDS/G': 'YDS/G'})

love_career['Opponent'] = love_career['Opponent'].map(team_name_map)
herbert_career['Opponent'] = herbert_career['Opponent'].map(team_name_map)
allen_career['Opponent'] = allen_career['Opponent'].map(team_name_map)
rodgers_career['Opponent'] = rodgers_career['Opponent'].map(team_name_map)
hurts_career['Opponent'] = hurts_career['Opponent'].map(team_name_map)
lawrence_career['Opponent'] = lawrence_career['Opponent'].map(team_name_map)
stafford_career['Opponent'] = stafford_career['Opponent'].map(team_name_map)
purdy_career['Opponent'] = purdy_career['Opponent'].map(team_name_map)

love_career = (love_career[['Opponent', 'YDS/G']])
herbert_career = (herbert_career[['Opponent', 'YDS/G']])
allen_career = (allen_career[['Opponent', 'YDS/G']])
rodgers_career = (rodgers_career[['Opponent', 'YDS/G']])
hurts_career = (hurts_career[['Opponent', 'YDS/G']])
lawrence_career = (lawrence_career[['Opponent', 'YDS/G']])
stafford_career = (stafford_career[['Opponent', 'YDS/G']])
purdy_career = (purdy_career[['Opponent', 'YDS/G']])
# If you have a Josh Allen career dataframe, do the same

# Drop all rows with any NA values
love_career = love_career.dropna()
herbert_career = herbert_career.dropna()
allen_career = allen_career.dropna()
rodgers_career = rodgers_career.dropna()
hurts_career = hurts_career.dropna()
lawrence_career = lawrence_career.dropna()
stafford_career = stafford_career.dropna()
purdy_career = purdy_career.dropna()
# If you have a Josh Allen career dataframe, do the same


# Reset the index after dropping
love_career = love_career.reset_index(drop=True)
herbert_career = herbert_career.reset_index(drop=True)
allen_career = allen_career.reset_index(drop=True)
rodgers_career = rodgers_career.reset_index(drop=True)
hurts_career = hurts_career.reset_index(drop=True)
lawrence_career = lawrence_career.reset_index(drop=True)
stafford_career = stafford_career.reset_index(drop=True)
purdy_career = purdy_career.reset_index(drop=True)
# If you have a Josh Allen career dataframe, do the same

# Rename columns for clarity
love_clean = love_career.rename(columns={'YDS/G': 'love_avg', 'Opponent': 'Team'})
herbert_clean  = herbert_career.rename(columns={'YDS/G': 'herbert_avg', 'Opponent': 'Team'})
allen_clean = allen_career.rename(columns={'YDS/G': 'allen_avg', 'Opponent': 'Team'})
rodgers_clean = rodgers_career.rename(columns={'YDS/G': 'rodgers_avg', 'Opponent': 'Team'})
hurts_clean = hurts_career.rename(columns={'YDS/G': 'hurts_avg', 'Opponent': 'Team'})
lawrence_clean = lawrence_career.rename(columns={'YDS/G': 'lawrence_avg', 'Opponent': 'Team'})
stafford_clean = stafford_career.rename(columns={'YDS/G': 'stafford_avg', 'Opponent': 'Team'})
purdy_clean = purdy_career.rename(columns={'YDS/G': 'purdy_avg', 'Opponent': 'Team'})
# If you have a Josh Allen career dataframe, do the same

# Merge Love and Herbert first
combined = love_clean.merge(herbert_clean, on='Team', how='outer')

# Merge Allen
combined = combined.merge(allen_clean, on='Team', how='outer')

# Merge Rodgers
combined = combined.merge(rodgers_clean, on='Team', how='outer')
#Merge Hurts
combined = combined.merge(hurts_clean, on='Team', how='outer')

#Merdge Lawrence
combined = combined.merge(lawrence_clean, on='Team', how='outer')

#Merdge Stafford
combined = combined.merge(stafford_clean, on='Team', how='outer')

# Merdge Purdy
combined = combined.merge(purdy_clean, on='Team', how='outer')

# Defensive yards allowed
defense_yards = passing_defense_2025[['Tm', 'Y/G']].copy()

# Jordan Love
love_2025 = love_2025[['Opp', 'Yds']]
love_2025 = love_2025.iloc[::-1].reset_index(drop=True)  # reverse order
love_2025['Game'] = range(1, len(love_2025) + 1)

# Justin Herbert
herbert_2025 = herbert_2025[['Opp', 'Yds']]
herbert_2025 = herbert_2025.iloc[::-1].reset_index(drop=True)
herbert_2025['Game'] = range(1, len(herbert_2025) + 1)

# Josh Allen
allen_2025 = allen_2025[['Opp', 'Yds']]
allen_2025 = allen_2025.iloc[::-1].reset_index(drop=True)
allen_2025['Game'] = range(1, len(allen_2025) + 1)

#Aaron Rodgers
rodgers_2025 = rodgers_2025[['Opp', 'Yds']]
rodgers_2025 = rodgers_2025.iloc[::-1].reset_index(drop=True)
rodgers_2025['Game'] = range(1, len(rodgers_2025) + 1)

#Jalen Hurts
hurts_2025 = hurts_2025[['Opp', 'Yds']]
hurts_2025 = hurts_2025.iloc[::-1].reset_index(drop=True)
hurts_2025['Game'] = range(1, len(hurts_2025) + 1)

#Trevor Lawrence
lawrence_2025 = lawrence_2025[['Opp', 'Yds']]
lawrence_2025 = lawrence_2025.iloc[::-1].reset_index(drop=True)
lawrence_2025['Game'] = range(1, len(lawrence_2025) + 1)



#Matt Stafford
stafford_2025 = stafford_2025[['Opp', 'Yds']]
stafford_2025 = stafford_2025.iloc[::-1].reset_index(drop=True)
stafford_2025['Game'] = range(1, len(stafford_2025) + 1)

#Brock Purdy
purdy_2025 = purdy_2025[['Opp', 'Yds']]
purdy_2025 = purdy_2025.iloc[::-1].reset_index(drop=True)
purdy_2025['Game'] = range(1, len(purdy_2025) + 1)

# Apply mapping
defense_yards['Tm'] = defense_yards['Tm'].map(team_name_map)

def predict_single_game(qb_name, opp_team_abbr, combined, defense_yards, game_log=None, ci=0.9):


    # Map QB name to column in combined
    qb_col_map = {
        'Jordan Love': 'love_avg',
        'Justin Herbert': 'herbert_avg',
        'Josh Allen': 'allen_avg',
        'Aaron Rodgers': 'rodgers_avg',
        'Jalen Hurts': 'hurts_avg',
        'Trevor Lawrence': 'lawrence_avg',
        'Matt Stafford': 'stafford_avg',
        'Brock Purdy': 'purdy_avg'
    }
    if qb_name not in qb_col_map:
        raise ValueError(f"{qb_name} not in combined table")

    # 1️ Career average
    career_avg = combined.loc[combined['Team'] == opp_team_abbr, qb_col_map[qb_name]].values
    if len(career_avg) == 0 or np.isnan(career_avg[0]):
        career_avg = np.nanmean(combined[qb_col_map[qb_name]].values)  # fallback to league/QB average
    else:
        career_avg = career_avg[0]

    # 2️ Defensive strength
    def_pass = defense_yards.loc[defense_yards['Tm'] == opp_team_abbr, 'Y/G'].values
    if len(def_pass) == 0 or np.isnan(def_pass[0]):
        def_pass = defense_yards['Y/G'].mean()  # fallback to league average
    def_pass_scaled = def_pass / 300  # scale to ~0-1

    # 3️ Recent form (last 10 games)
    if game_log is not None and 'YDS/G' in game_log.columns and len(game_log) > 0:
        n_recent = min(10, len(game_log))
        recent_avg = game_log['YDS/G'].iloc[-n_recent:].mean()
        std_val = game_log['YDS/G'].iloc[-n_recent:].std()
        if std_val == 0 or np.isnan(std_val):
            recent_form = 0
        else:
            recent_form = (recent_avg - game_log['YDS/G'].mean()) / std_val
    else:
        recent_form = 0

    # 4️ Bayesian model
    with pm.Model() as model:
        sigma_h2h = pm.HalfNormal("sigma_h2h", 10)
        phi = pm.Normal("phi", mu=career_avg, sigma=sigma_h2h)
        beta_D = pm.Normal("beta_D", mu=0, sigma=10)
        beta_R = pm.Normal("beta_R", mu=0, sigma=10)
        alpha = pm.Normal("alpha", mu=0, sigma=15)
        sigma = pm.HalfNormal("sigma", 15)

        mu = phi - beta_D * def_pass_scaled + beta_R * recent_form + alpha

        trace = pm.sample(1000, tune=1000, chains=2, target_accept=0.95, progressbar=False)

    # 5️ Posterior predictive draws
    phi_post = trace.posterior['phi'].values.flatten()
    alpha_post = trace.posterior['alpha'].values.flatten()
    beta_D_post = trace.posterior['beta_D'].values.flatten()
    beta_R_post = trace.posterior['beta_R'].values.flatten()
    sigma_post = trace.posterior['sigma'].values.flatten()

    draws = np.random.normal(
        loc=alpha_post + phi_post - beta_D_post * def_pass_scaled + beta_R_post * recent_form,
        scale=sigma_post
    )

    median_pred = np.median(draws)
    lower = np.percentile(draws, (1-ci)/2*100)
    upper = np.percentile(draws, (1+ci)/2*100)

    return draws, median_pred, lower, upper

# RESULTS








results_df = pd.DataFrame(
    columns=["QB", "Opponent", "Median_Pass_Yds", "CI_Low", "CI_High"]
)

# Example: single prediction
qb_name = "Jordan Love"
opp_team_abbr = "CHI"
game_log = love_2025

draws, median_pred, ci_low, ci_high = predict_single_game(
    qb_name=qb_name,
    opp_team_abbr=opp_team_abbr,
    combined=combined,
    defense_yards=defense_yards,
    game_log=game_log,
    ci=0.9
)

# Append to DataFrame
results_df = pd.concat([
    results_df,
    pd.DataFrame([{
        "QB": qb_name,
        "Opponent": opp_team_abbr,
        "Median_Pass_Yds": median_pred,
        "CI_Low": ci_low,
        "CI_High": ci_high
    }])
], ignore_index=True)

# Make a single prediction for Justin Herbert vs NE
qb_name = "Justin Herbert"
opp_team_abbr = "NE"
game_log = herbert_2025

draws, median_pred, ci_low, ci_high = predict_single_game(
    qb_name=qb_name,
    opp_team_abbr=opp_team_abbr,
    combined=combined,
    defense_yards=defense_yards,
    game_log=game_log,
    ci=0.9  # 90% credible interval
)



# Append to your existing results_df
results_df = pd.concat([
    results_df,
    pd.DataFrame([{
        "QB": qb_name,
        "Opponent": opp_team_abbr,
        "Median_Pass_Yds": median_pred,
        "CI_Low": ci_low,
        "CI_High": ci_high
    }])
], ignore_index=True)

# Make a single prediction for Josh Allen vs Jax
qb_name = "Josh Allen"
opp_team_abbr = "JAX"
game_log = allen_2025

draws, median_pred, ci_low, ci_high = predict_single_game(
    qb_name=qb_name,
    opp_team_abbr=opp_team_abbr,
    combined=combined,
    defense_yards=defense_yards,
    game_log=game_log,
    ci=0.9  # 90% credible interval
)

# Print results
print(f"Median: {median_pred:.1f} yards")
print(f"90% CI: [{ci_low:.1f}, {ci_high:.1f}] yards")

# Append to your existing results_df
results_df = pd.concat([
    results_df,
    pd.DataFrame([{
        "QB": qb_name,
        "Opponent": opp_team_abbr,
        "Median_Pass_Yds": median_pred,
        "CI_Low": ci_low,
        "CI_High": ci_high
    }])
], ignore_index=True)

# Make a single prediction for Justin Herbert vs NE
qb_name = "Aaron Rodgers"
opp_team_abbr = "HOU"
game_log = rodgers_2025

draws, median_pred, ci_low, ci_high = predict_single_game(
    qb_name=qb_name,
    opp_team_abbr=opp_team_abbr,
    combined=combined,
    defense_yards=defense_yards,
    game_log=game_log,
    ci=0.9  # 90% credible interval
)

# Print results
print(f"Median: {median_pred:.1f} yards")
print(f"90% CI: [{ci_low:.1f}, {ci_high:.1f}] yards")

# Append to your existing results_df
results_df = pd.concat([
    results_df,
    pd.DataFrame([{
        "QB": qb_name,
        "Opponent": opp_team_abbr,
        "Median_Pass_Yds": median_pred,
        "CI_Low": ci_low,
        "CI_High": ci_high
    }])
], ignore_index=True)

# Make a single prediction for Jalen hurts vs SF
qb_name = "Jalen Hurts"
opp_team_abbr = "SF"
game_log = hurts_2025

draws, median_pred, ci_low, ci_high = predict_single_game(
    qb_name=qb_name,
    opp_team_abbr=opp_team_abbr,
    combined=combined,
    defense_yards=defense_yards,
    game_log=game_log,
    ci=0.9  # 90% credible interval
)


# Append to your existing results_df
results_df = pd.concat([
    results_df,
    pd.DataFrame([{
        "QB": qb_name,
        "Opponent": opp_team_abbr,
        "Median_Pass_Yds": median_pred,
        "CI_Low": ci_low,
        "CI_High": ci_high
    }])
], ignore_index=True)

# Make a single prediction for Brock Purdy vs PHI
qb_name = "Brock Purdy"
opp_team_abbr = "PHI"
game_log = purdy_2025

draws, median_pred, ci_low, ci_high = predict_single_game(
    qb_name=qb_name,
    opp_team_abbr=opp_team_abbr,
    combined=combined,
    defense_yards=defense_yards,
    game_log=game_log,
    ci=0.9  # 90% credible interval
)


# Append to your existing results_df
results_df = pd.concat([
    results_df,
    pd.DataFrame([{
        "QB": qb_name,
        "Opponent": opp_team_abbr,
        "Median_Pass_Yds": median_pred,
        "CI_Low": ci_low,
        "CI_High": ci_high
    }])
], ignore_index=True)

# Make a single prediction for Trevor Lawrence vs BUF
qb_name = "Trevor Lawrence"
opp_team_abbr = "BUF"
game_log = lawrence_2025

draws, median_pred, ci_low, ci_high = predict_single_game(
    qb_name=qb_name,
    opp_team_abbr=opp_team_abbr,
    combined=combined,
    defense_yards=defense_yards,
    game_log=game_log,
    ci=0.9  # 90% credible interval
)

# Print results
#print(f"Median: {median_pred:.1f} yards")
#print(f"90% CI: [{ci_low:.1f}, {ci_high:.1f}] yards")

# Append to your existing results_df
results_df = pd.concat([
    results_df,
    pd.DataFrame([{
        "QB": qb_name,
        "Opponent": opp_team_abbr,
        "Median_Pass_Yds": median_pred,
        "CI_Low": ci_low,
        "CI_High": ci_high
    }])
], ignore_index=True)

# Make a single prediction for Stafford vs CAR
qb_name = "Matt Stafford"
opp_team_abbr = "CAR"
game_log = stafford_2025

draws, median_pred, ci_low, ci_high = predict_single_game(
    qb_name=qb_name,
    opp_team_abbr=opp_team_abbr,
    combined=combined,
    defense_yards=defense_yards,
    game_log=game_log,
    ci=0.9  # 90% credible interval
)


# Append to your existing results_df
results_df = pd.concat([
    results_df,
    pd.DataFrame([{
        "QB": qb_name,
        "Opponent": opp_team_abbr,
        "Median_Pass_Yds": median_pred,
        "CI_Low": ci_low,
        "CI_High": ci_high
    }])
], ignore_index=True)


# Save results_df to CSV so app.py can just read it
results_df.to_csv("results_df.csv", index=False)
